const Worklocations = [
  {
    id: "1",
    name: "Head Office",
    address: "Galle Road  Ratmalana",
    locationType: "HO",
  },
  {
    id: "2",
    name: "RSC (Western Central)",
    address: "Nawala",
    locationType: "RSC",
  },
  {
    id: "3",
    name: "Regional Manager (Colombo City S/W)",
    address: "Maligakanda",
    locationType: "RO",
  },
  {
    id: "4",
    name: "Regional Manager (Colombo City N/E)",
    address: "Maligakanda",
    locationType: "RO",
  },
  {
    id: "5",
    name: "Regional Manager (Kotte)",
    address: "Kotte",
    locationType: "RO",
  },
  {
    id: "6",
    name: "Regional Manager (Maharagama)",
    address: "Makumbura",
    locationType: "RO",
  },
  {
    id: "7",
    name: "RSC (Production - Ambatale) ",
    address: "Ambatale",
    locationType: "RSC",
  },
  {
    id: "8",
    name: "RSC (Western South)",
    address: "No. 07, Angulana Station Road, Moratuwa",
    locationType: "RSC",
  },
  {
    id: "9",
    name: "Regional Manager (Dehiwala)",
    address: "Dehiwala",
    locationType: "RO",
  },
  {
    id: "10",
    name: "Regional Manager (Panadura/ Horana)",
    address: "Panadura",
    locationType: "RO",
  },
  {
    id: "11",
    name: "Regional Manager (Kalutara)",
    address: "Kalutara",
    locationType: "RO",
  },
  {
    id: "12",
    name: "RSC (Southern)",
    address: "Matara",
    locationType: "RSC",
  },
  {
    id: "13",
    name: "Regional Manager (Matara)",
    address: "Matara",
    locationType: "RO",
  },
  {
    id: "14",
    name: "Regional Manager (Hambantota)",
    address: "Hambantota",
    locationType: "RO",
  },
  {
    id: "15",
    name: "Regional Manager (Galle)",
    address: "Galle",
    locationType: "RO",
  },
  {
    id: "16",
    name: "RSC (Sabaragamuwa)",
    address: "Avissawella",
    locationType: "RSC",
  },
  {
    id: "17",
    name: "Regional Manager (Ratnapura)",
    address: "Ratnapura",
    locationType: "RO",
  },
  {
    id: "18",
    name: "Regional Manager (Kegalle)",
    address: "Kegalle",
    locationType: "RO",
  },
  {
    id: "19",
    name: "RSC (Uva)",
    address: "Bandarawela",
    locationType: "RSC",
  },
  {
    id: "20",
    name: "Regional Manager (Bandarawela)",
    address: "Bandarawela",
    locationType: "RO",
  },
  {
    id: "21",
    name: "Regional Manager (Monaragala)",
    address: "Monaragala",
    locationType: "RO",
  },
  {
    id: "22",
    name: "RSC (Central)",
    address: "Kandy",
    locationType: "RSC",
  },
  {
    id: "23",
    name: "Regional Manager (Kandy East)",
    address: "Katugasthota",
    locationType: "RO",
  },
  {
    id: "24",
    name: "Regional Manager (Kandy South)",
    address: "Peradeniya",
    locationType: "RO",
  },
  {
    id: "25",
    name: "Regional Manager (Kandy North)",
    address: "Kundasale",
    locationType: "RO",
  },
  {
    id: "26",
    name: "RSC (East)",
    address: "Trincomalee",
    locationType: "RSC",
  },
  {
    id: "27",
    name: "Regional Manager (Trincomalee)",
    address: "Trincomalee",
    locationType: "RO",
  },
  {
    id: "28",
    name: "Regional Manager (Ampara)",
    address: "Ampara",
    locationType: "RO",
  },
  {
    id: "29",
    name: "Regional Manager (Akkaraipattu)",
    address: "Akkaraipattu",
    locationType: "RO",
  },
  {
    id: "30",
    name: "Regional Manager (Batticalo)",
    address: "Batticalo",
    locationType: "RO",
  },
  {
    id: "31",
    name: "RSC (North Central)",
    address: "Anuradhapura",
    locationType: "RSC",
  },
  {
    id: "32",
    name: "Regional Manager (Anuradhapura) ",
    address: "Anuradhapura",
    locationType: "RO",
  },
  {
    id: "33",
    name: "RSC (Sewerage)",
    address: "Galle Road  Ratmalana",
    locationType: "RSC",
  },
  {
    id: "34",
    name: "Regional Manager Sewerage (Jayawadanagama) ",
    address: "Jayawadanagama",
    locationType: "RO",
  },
  {
    id: "35",
    name: "Regional Manager Sewerage (Dehiwala / Mt. Lavinia)",
    address: "Dehiwala",
    locationType: "RO",
  },
  {
    id: "36",
    name: "Regional Manager Sewerage (Seethawakapura) ",
    address: "Seethawakapura",
    locationType: "RO",
  },
  {
    id: "37",
    name: "RSC (North Western)",
    address: "Kurunegala",
    locationType: "RSC",
  },
  {
    id: "38",
    name: "Regional Manager (Kurunegala)",
    address: "Kurunegala",
    locationType: "RO",
  },
  {
    id: "39",
    name: "RSC (Western North)",
    address: "Kadawatha",
    locationType: "RSC",
  },
  {
    id: "40",
    name: "Regional Manager (Gampaha) ",
    address: "Gampaha ",
    locationType: "RO",
  },
  {
    id: "41",
    name: "Regional Manager (Kelaniya) ",
    address: "Kelaniya",
    locationType: "RO",
  },
  {
    id: "42",
    name: "RSC (North)",
    address: "Vavuniya",
    locationType: "RSC",
  },
  {
    id: "43",
    name: "Regional Manager (Jaffna) ",
    address: "Jaffna",
    locationType: "RO",
  },
  {
    id: "44",
    name: "Regional Manager (Vavuniya)",
    address: "Vavuniya",
    locationType: "RO",
  },
  {
    id: "45",
    name: "Regional Manager Sewerage( Ja-ela Ekala)",
    address: "Regional Manager Sewerage( Ja-ela Ekala)",
    locationType: "RO",
  },
  {
    id: "46",
    name: "RSC (Western East)",
    address: "RSC (Western East)",
    locationType: "RSC",
  },
  {
    id: "47",
    name: "Regional Manager (Polonnaruwa)",
    address: "Regional Manager (Polonnaruwa)",
    locationType: "RO",
  },
  {
    id: "48",
    name: "Regional Manager (Puttalam)",
    address: "Puttalam",
    locationType: "RO",
  },
];

function getWorklocationById(id) {
  return Worklocations.find((location) => location.id === id);
}

export { Worklocations, getWorklocationById };
